# Basic flutter build

# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

# clone the latest source codes 
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/bwnyasse/flutter-testing-tutorial.git']
  dir: '/workspace'

# INTEGRATION : To run flutter build apk, one must need to  be at the root of the project, 
# the script simply cd to the root before running the build command
#-------------------------------------------------------------------------------------------
- name: 'gcr.io/$PROJECT_ID/flutter'
  entrypoint: '/bin/bash'
  args: ['cloudbuild.sh', 'flutter-testing-tutorial']

# DEPLOYMENT: apk artifacts can be pushed to a GCS bucket like this
#------------------------------------------------------------------
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['cp', '/workspace/flutter/examples/hello_world/build/app/outputs/apk/release/app-release.apk', 'gs://$MY_BUCKET/hello_world.apk']

# DELIVERY : upload apk to google play store with Fastlane
#-----------------------------------------------------------
#- name: 'gcr.io/$PROJECT_ID/fastlane'
#  args: ['supply', '--package_name','${_ANDROID_PACKAGE_NAME}', '--track', '${_ANDROID_RELEASE_CHANNEL}', '--json_key_data', '${_GOOGLE_PLAY_UPLOAD_KEY_JSON}', '--apk', '/workspace/${_REPO_NAME}/build/app/outputs/apk/release/app-release.apk']
#timeout: 1200s

tags: ['cloud-builders-community']