// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_movie_deep_dive_test/test/src/blocs/app_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:flutter_movie_deep_dive_test/src/models/models.dart' as _i3;
import 'package:flutter_movie_deep_dive_test/src/services/app_service.dart'
    as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

class _FakeMoviesResponse_1 extends _i1.Fake implements _i3.MoviesResponse {}

/// A class which mocks [AppService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppService extends _i1.Mock implements _i4.AppService {
  MockAppService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i5.Future<_i3.MoviesResponse> loadMovies() =>
      (super.noSuchMethod(Invocation.method(#loadMovies, []),
              returnValue:
                  Future<_i3.MoviesResponse>.value(_FakeMoviesResponse_1()))
          as _i5.Future<_i3.MoviesResponse>);
  @override
  String toString() => super.toString();
}
